### PR TITLE
Updated for new version of log4net,ms.bcl, ms.net.http, newtsoft.json

### PR DESCRIPTION
**Pull request by hmol**
Updated for new version of log4net, ms.bcl, ms.net.http, newtsoft.json and removed unused code.

### CODE REVIEW

**Comment by dnasir** [comment]
@hmol 

Thanks for the pull request. I'm looking into this now.

Do you know if the new version of log4net will be compatible with older versions of EPiServer 7? Because I see that you've also updated this package, and I'm wondering if it will break the plugin for older EPiServer 7 installations.

**Comment by hmol** [comment]
I just ran a nuget package update, then included this new Log4NetLogglyAppender .dll into my project to test it and it worked with newest EPi version :)
Have not tested it with EPi 7.

**Comment by valdisiljuconoks** [comment]
Can you please push out NuGet package for this?

**Comment by hmol** [comment]
Yes that would be great :smiley:

**Pull request merged**
